# @see https://github.com/actions/upload-release-asset
name: Release and Upload Assets for 9.2-2019.12

on:
  push:
    branch:
    - 'main'

env:
  TAG: 9.2-2019.12
  AARCH32: gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.tar.xz
  AARCH64: gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    # @see https://ryangjchandler.co.uk/articles/running-github-actions-for-certain-commit-messages
    if: "startsWith(${{ github.event.head_commit.message }},'feature(9.2-2019.12)')"
    steps:
      - uses: actions/checkout@v2
      - name: Download from binrel
        env:
          REPO: https://developer.arm.com/-/media/Files/downloads/gnu-a
        run: |
          curl -LO $REPO/$TAG/binrel/$AARCH32 &&
          curl -LO $REPO/$TAG/binrel/$AARCH64
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ env.TAG }}-${{ steps.parse_committed_at.outputs.committedAt }}
#          release_name: Release ${{ env.TAG }}-${{ steps.parse_committed_at.outputs.committedAt }}
#          draft: false
#          prerelease: false
      # release should has been created before
      - name: Get 'upload_url'
        env:
          TAG: ${{ env.TAG }}
        id: get_upload_url
        run: bash scripts/get_upload_url.sh
      - name: Upload ${{ env.AARCH32 }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_upload_url.outputs.url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./${{ env.AARCH32 }}
          asset_name: ${{ env.AARCH32 }}
          # https://en.wikipedia.org/wiki/List_of_archive_formats
          asset_content_type: application/x-gtar
      - name: Upload ${{ env.AARCH64 }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./${{ env.AARCH64 }}
          asset_name: ${{ env.AARCH64 }}
          # https://en.wikipedia.org/wiki/List_of_archive_formats
          asset_content_type: application/x-gtar
